stages:
  - lint
  - test

.common:
  image: ${DOCKER_PROXY_URL}/golang:1.20.2
  tags:
    - sts-k8s-m-runner

lint:
  extends: .common
  stage: lint
  script:
    - go fmt ./...
    - go install github.com/mgechev/revive@latest
    - revive -formatter stylish -config revive-recommended.toml ./...

test:
  extends: .common
  stage: test
  script:
    - go test -v ./...
